# Generated by Django 4.2.9 on 2024-01-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя автора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='информация об авторе')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=64, unique=True, verbose_name='Google id')),
                ('title', models.CharField(max_length=128, verbose_name='Название книги')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание книги')),
                ('isbn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ISBN код')),
                ('info_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на книгу')),
                ('year', models.CharField(blank=True, max_length=16, null=True, verbose_name='Год издания')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Кол-во страниц')),
                ('authors', models.ManyToManyField(to='app.author', verbose_name='список авторов')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_of_study', models.CharField(max_length=128, verbose_name='направление обучения')),
                ('university', models.CharField(max_length=128, verbose_name='университет')),
                ('year', models.IntegerField(default=2024, verbose_name='год принятия')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название дисциплины')),
                ('books', models.ManyToManyField(to='app.book', verbose_name='список книг')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.syllabus', verbose_name='учебный план')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
