# Generated by Django 4.2.9 on 2024-05-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_userfavorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfavorite",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_favorites",
                to="app.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Аккаунт",
            ),
        ),
        migrations.CreateModel(
            name="UserUniversities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Имя университета",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="app.syllabus",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунт",
                    ),
                ),
            ],
        ),
    ]
